gems:
  - jemoji
  - jekyll-paginate

name: 'SWCODE'
title: "SWCODE BLOG"
description: >
   Articles from our daily dev work
email: developers@swcode.io

logo: "/assets/images/logo_quad.png"
teaserlogo: "/assets/images/logo.jpg"
float_logo: true
cover: "/assets/images/pattern.jpg"

paginate:	10
permalink: pretty

url: "https://blog.swcode.io"
baseurl: ""

matomo:
  site_id: 10
  tag_manager_container_id: "f6aOsDl3"

utterances:
  repo: "sw-code/sw-code.github.io"
  issue_term: "pathname"
  label: "blogcomment"
  theme: "github-light"

newsletter:
  registration_url: https://1cfc5ec7.sibforms.com/serve/MUIFACO5cBBoo1-tWYwcHrThrrLYLuje1g4WGaG3tTp2gWCvNxIaPKnf0VxRdZTwgXNkQseMirZ_S_jZvFIhI2YnTt2ffrHH0--uF2iVLvaEpDDLg_7rY_pENdtRhGO0RiSkB4JLonAG1W44LqpvzeVbSfHTdQ3SeBbDFjb3-grRUPo0Ak5q36Mcl76wNLdOGJic98aojSVnK45T

social:
  - icon:	linkedin
    url:	https://www.linkedin.com/company/69717870
    desc: Follow us on Linkedin
    share_url: https://www.linkedin.com/sharing/share-offsite
    share_title: ?title=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/sw-code
    desc:	Fork us on github
    share_url:
    share_title:
    share_link: