# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "SWCODE BLOG"
description: > # this means to ignore newlines until "email:"
   Articles from our daily dev work

email: developers@swcode.io
#blog logo
logo: "/assets/images/logo_quad.png"
teaserlogo: "/assets/images/logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/pattern.jpg"

name: 'SWCODE'

paginate:	10

url: "httpsZ://blog.swcode.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://www.linkedin.com/company/69717870
    desc: Follow us on Linkedin
    share_url: https://www.linkedin.com/sharing/share-offsite
    share_title: ?title=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/sw-code
    desc:	Fork us on github
    share_url:
    share_title:
    share_link: