gems:
  - jemoji
  - jekyll-paginate

name: 'SWCODE'
title: "SWCODE BLOG"
description: >
   Articles from our daily dev work
email: developers@swcode.io

logo: "/assets/images/logo_quad.png"
teaserlogo: "/assets/images/logo.jpg"
float_logo: true
cover: "/assets/images/pattern.jpg"

paginate:	10
permalink: pretty

url: "https://blog.swcode.io"
baseurl: ""

social:
  - icon:	linkedin
    url:	https://www.linkedin.com/company/69717870
    desc: Follow us on Linkedin
    share_url: https://www.linkedin.com/sharing/share-offsite
    share_title: ?title=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/sw-code
    desc:	Fork us on github
    share_url:
    share_title:
    share_link: